_wandb:
    value:
        cli_version: 0.23.1
        e:
            t6xmzzcwxqkvew7eucqa4w8vohvnb6iz:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    memoryGb: 16
                    name: Apple M5
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "15032385536"
                codePath: hw1/src/hw1_imitation/train.py
                codePathLocal: src/hw1_imitation/train.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494332366848"
                        used: "467256143872"
                email: xiepin225@gmail.com
                executable: /Users/stephenxie/Documents/GitHub/homework_spring2026/hw1/.venv/bin/python3
                git:
                    commit: 58f55d94db422d761a33a8669af3c01668db877e
                    remote: https://github.com/berkeleydeeprlcourse/homework_spring2026.git
                host: wifi-10-44-52-205.wifi.berkeley.edu
                memory:
                    total: "17179869184"
                os: macOS-26.2-arm64-arm-64bit
                program: /Users/stephenxie/Documents/GitHub/homework_spring2026/hw1/src/hw1_imitation/train.py
                python: CPython 3.11.13
                root: /Users/stephenxie/Documents/GitHub/homework_spring2026/hw1
                startedAt: "2026-01-29T01:39:48.622532Z"
                writerId: t6xmzzcwxqkvew7eucqa4w8vohvnb6iz
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.11.13
            "5": 0.23.1
            "8":
                - 2
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 256
chunk_size:
    value: 8
data_dir:
    value: data
eval_interval:
    value: 10000
exp_name:
    value: null
flow_num_steps:
    value: 20
hidden_dims:
    value:
        - 256
        - 256
        - 256
log_interval:
    value: 100
lr:
    value: 0.005
num_epochs:
    value: 400
num_video_episodes:
    value: 5
policy_type:
    value: mse
seed:
    value: 42
video_size:
    value:
        - 256
        - 256
wandb_project:
    value: hw1-imitation
warmup_steps:
    value: 5000
weight_decay:
    value: 0.1
